JackAnalyzer: jacktokenizer.cpp xmlcompiler.cpp vmcompiler.cpp jackanalyzer.cpp main.cpp symboltable.cpp
	gcc -std=c++11 -Wall -g -o $@ jacktokenizer.cpp xmlcompiler.cpp vmcompiler.cpp jackanalyzer.cpp main.cpp symboltable.cpp -lstdc++
